"""
Influence 720 — Data Foundation v2.
Builds the deterministic scaffolding (constants, sourced role taxonomy, coverage catalog,
GWP pricing engine, producer roster, flagship-account re-expression, and the 143-new-account
allocation) that the per-account narrative-authoring agent fan-out fills in.

Everything in this file is either (a) copied verbatim from 360's own code (cited to
01-plan/DATA_FOUNDATION_BRIEF.md §2), (b) sourced from the brief's §4 role taxonomy /
§6 schema corrections / §7 pricing corrections, or (c) an explicitly labeled estimate where
the brief itself found no citable source. Nothing here is invented without a flag.

Referential integrity (IDs, enum values, edge targets) is intentionally kept OUT of the
agent fan-out and done here + in assemble_v2.py — see HANDOVER_360_TO_720.md §2.6's root
cause (data layer grew reactively, patched after the fact) for why.
"""
import json
import random

BUILD_DIR = "/Users/celeste7/Documents/INFLUENCE/05-build/generator/build_v2"

# GENERATED by integrate_vertical_ontology.py from the vertical-ontology-expansion Workflow —
# 9-segment canonical lifecycle taxonomy (yacht remapped from 360's own 7-of-9-populated set,
# aviation/real_estate/auto/personal newly researched to the same depth). Do not hand-edit —
# re-run the Workflow + integrate_vertical_ontology.py to regenerate role_taxonomy_generated.py.
# Imported early (before DOMAINS_BY_VERTICAL below, which references SEGMENTS directly).
from role_taxonomy_generated import ROLE_TAXONOMY, SEGMENTS  # noqa: F401

# ============================================================================
# TEMPLATE_ROLE_META — 2026-08-16: keyed lookup onto template_ontology.json's per-role
# firms/vessel_relevance/coi_influence/subgroup/micro_nodes (merged in from the yacht-vertical
# port + 4-vertical research agent outputs). This is the single source both
# flagship_and_allocate_v2.py and assemble_v2.py read from to propagate template-level constants
# onto every REAL per-account role instance — a real "Captain" instance on account X carries the
# same firms/vessel_relevance/coi_influence/subgroup as the template "Captain" role. Keyed by
# (vertical, title) since that's how a real instance's title always traces back to its template row.
# ============================================================================
with open(f"{BUILD_DIR}/template_ontology.json") as _tf:
    _TEMPLATE_ONTOLOGY = json.load(_tf)

TEMPLATE_ROLE_META = {}
for _v, _vdata in _TEMPLATE_ONTOLOGY["verticals"].items():
    for _r in _vdata["roles"]:
        TEMPLATE_ROLE_META[(_v, _r["title"])] = {
            "firms": _r.get("firms", ""),
            "vessel_relevance": _r.get("vessel_relevance", {}),
            "coi_influence": _r.get("coi_influence", ""),
            "subgroup": _r.get("subgroup", ""),
            "micro_nodes": _r.get("micro_nodes", []),
        }

# ============================================================================
# §2 — 360's exact reusable constants (DATA_FOUNDATION_BRIEF.md §2, verbatim)
# ============================================================================

RI = {0: 80, 1: 210, 2: 400, 3: 630, 4: 840}
RO = {0: 200, 1: 390, 2: 620, 3: 830, 4: 1020}
RC = {0: '#6a9de0', 1: '#c9a84c', 2: '#e07a30', 3: '#4a8aba', 4: '#2e5070'}
RL = {0: 'APEX', 1: 'COI SIGNATORY', 2: 'COI CONDITIONAL', 3: 'TRANSACTION CRITICAL', 4: 'OPERATIONAL'}

# DOMAINS[7] said "Management & Crew" (the sector wedge that actually renders) vs DOM_NAMES'
# "Manning & Crew" (panel badge only) — brief §2.1: "decide once, which string wins." The
# rendered sector wedge wins; "Management & Crew" is what 720 uses everywhere.
DOMAINS_YACHT = [
    {"id": 1, "name": "Ownership & Structure", "col": "#6a9de0"},
    {"id": 2, "name": "Legal & Finance", "col": "#3a7fd4"},
    {"id": 3, "name": "Flag · Class & Compliance", "col": "#2a9a8a"},
    {"id": 4, "name": "Insurance Market", "col": "#c9a84c"},
    {"id": 5, "name": "Acquisition & Sale", "col": "#6aaa44"},
    {"id": 6, "name": "New Build & Refit", "col": "#e07a30"},
    {"id": 7, "name": "Management & Crew", "col": "#cc5555"},
    {"id": 8, "name": "Charter & Guest Ops", "col": "#aa44aa"},
    {"id": 9, "name": "Operations & Shoreside", "col": "#4488aa"},
]

# coi_type enum — brief §2.5: normalize transactional -> transaction (same concept, never
# normalized in 360 itself); regulatory/adjacent are REAL 360 values (7 + 2 of 187 nodes) that
# 360's own UI never gave a label/CSS/filter to — 720's data now uses them with real content,
# schema/README flags that the HTML-layer label/CSS/filter support is still an open follow-up.
COI_TYPE_ENUM = ["signatory", "conditional", "transaction", "operational", "regulatory", "adjacent", "none"]

# vessel_relevance size-class scale — brief §2.8, verbatim from 360's own filter dropdown.
# "No named industry source for the exact breakpoints — treat as informed practitioner scale."
SIZE_CLASSES_YACHT = {
    "S1": "Under 15m — Day boat", "S2": "15-24m — Small yacht", "S3": "24-40m — Mid-range",
    "S4": "40-60m — Entry superyacht", "S5": "60-80m — Full-code superyacht",
    "S6": "80-100m — Large superyacht", "S7": "Over 100m — Gigayacht",
}

# ============================================================================
# DOMAINS_BY_VERTICAL — SUPERSEDED 2026-08-16: the prior version gave each vertical a
# DIFFERENT, much smaller domain count (aviation=4, real_estate=3, auto=2, personal=2) —
# exactly the "flattening" the founder flagged directly ("yachts and aviation and other
# domains are NEVER flattened. they are parallel within same universe"). Every vertical now
# shares the SAME 9 canonical lifecycle segments (SEGMENTS, from role_taxonomy_generated.py —
# a direct generalization of 360's own 9 domain ids/names/colors), populated with real,
# vertical-specific roles at equal structural depth. fine_art stays its own single-domain
# scope (never part of this directive — a scheduled-property program, not a lifecycle asset).
# ============================================================================
DOMAINS_BY_VERTICAL = {
    "yacht": {"count": 9, "list": SEGMENTS},
    "aviation": {"count": 9, "list": SEGMENTS},
    "real_estate": {"count": 9, "list": SEGMENTS},
    "auto": {"count": 9, "list": SEGMENTS},
    "personal": {"count": 9, "list": SEGMENTS},
    "fine_art": {"count": 1, "list": [
        {"id": 1, "name": "Collections & Scheduled Property", "col": "#aa44aa"},
    ]},
}

N_DOMAINS_BY_VERTICAL = {v: d["count"] for v, d in DOMAINS_BY_VERTICAL.items()}

# ============================================================================
# §4 — Sourced vertical role taxonomy (DATA_FOUNDATION_BRIEF.md §4). Each entry:
# (title, ring, coi_type, domain_id, category, source_tag)
# Ring/coi_type/domain assignment is MY mapping from the brief's prose purchasing-authority
# description onto 360's existing ring/coi_type/domain machinery — the brief gave sourced
# TITLES and authority DESCRIPTIONS, not ring numbers (360's own numeric scale is 720-specific
# machinery the brief's research streams were never asked to assign). Documented here, not
# silently asserted as sourced.
# ============================================================================
# (ROLE_TAXONOMY imported at the top of this file, before DOMAINS_BY_VERTICAL — see there.)

# ============================================================================
# §6 — Coverage catalog with corrections: Policy parent, trigger_type, line_of_business,
# "Liability Protection" (not P&I) for private/pleasure yachts, Fine Art as its own asset
# class/vertical (not nested under Yacht), Exec D&O entity-triggered.
# trigger_type in {asset, entity, activity, person} — brief §6 item 4.
#
# GENERATED/MERGED 2026-08-16: catalog depth extended from 5 vertical-specialist research
# agents (coverage_research_v2.json) — every pre-existing entry keeps its exact coverage_type_id
# (referential integrity for prefill_v2.py/assemble_v2.py/pricing_v2.py, which key off these
# ids) and gains required_baseline_limit/statutory_triggers/sub_limit_exclusions/cascade_rules;
# every "is_new": true entry in the research is a genuinely new coverage_type_id appended here.
# statutory_triggers/sub_limit_exclusions/cascade_rules are parsed into native Python
# lists-of-dicts (the research JSON carries them as escaped JSON-string values) so downstream
# code (gen_coverage_corpus.py, build_master_excel.py) can consume them directly and
# json.dumps() them back out for Excel/JSON export. Do not hand-edit the merged fields below —
# re-run against a refreshed coverage_research_v2.json instead.
# ============================================================================
with open(f"{BUILD_DIR}/coverage_research_v2.json") as _cf:
    _COVERAGE_RESEARCH = json.load(_cf)

# note text preserved from the pre-research catalog — brief §6 item 5, not carried in the
# research payload (which only adds the 4 new fields, not this project-specific annotation).
_COVERAGE_CATALOG_NOTES = {
    ("yacht", "liability_protection"): (
        "Renamed from P&I — brief §6 item 5: Chubb's real retail yacht product never uses 'P&I' "
        "for private/pleasure craft; reserved for commercially-coded/charter-registered yachts."
    ),
}

# ============================================================================
# 2026-08-16 (limit-deficiency pass) — baseline_limit_usd / baseline_limit_by_tier: a CLEAN
# NUMBER structured out of each entry's own required_baseline_limit PROSE above (never a new
# external figure). Convention: the baseline is the cited FLOOR/minimum a properly-limited
# account should carry — not the top of a cited range — since "baseline" here means the
# adequacy bar the forensic-audit engine checks bound_limit_usd against, not an aspirational
# ceiling. Two shapes:
#   - baseline_limit_by_tier: only for yacht (real S1-S7 size_class on every yacht Asset row)
#     and aviation (the light/mid/heavy tier pricing_v2.aviation_tier() already derives from
#     the asset label) — the two verticals whose prose explicitly scales the limit by asset
#     size AND whose Asset rows actually carry a usable tier key. real_estate/auto/personal/
#     fine_art Asset rows all carry size_class="N/A" (checked live against the master
#     workbook), so those verticals get a single flat baseline_limit_usd instead, per the
#     task's own "or a single flat baseline_limit_usd where it doesn't [tier]" instruction.
#   - Where prose cites an explicit tier-by-tier scale (e.g. liability_protection's
#     "$5,000,000 minimum for S1-S3... scaling to $25,000,000+ ... for S4-S7") the cited
#     numbers are used directly. Where prose only anchors ONE tier band (e.g. hull_machinery's
#     "$8,000,000-$150,000,000+ for S4-S7 (40m+)") the remaining S1-S3 (or S1-S4) tiers are
#     interpolated from the SAME cited anchor using ordinary yacht-value-by-length market
#     convention — exactly the same "no named industry source for the exact breakpoints,
#     treat as informed practitioner scale" discipline SIZE_CLASSES_YACHT above already uses,
#     never a fabricated new external citation. Where prose gives a ratio/ratio instruction
#     with no fixed dollar anchor of its own (e.g. increased_value_excess_liabilities' "20-30%
#     of hull value"), the ratio is applied to THIS SAME table's own hull_machinery figures —
#     grounded in-prose, not invented externally.
# ============================================================================

# yacht hull value baseline by size_class — grounds hull_machinery directly; every other
# yacht tiered entry below that "matches" or ratios off hull value reads from this same dict.
# S4=$10M/S7=$130M sit inside hull_machinery's own cited "$8,000,000-$150,000,000+ for S4-S7"
# band; S1-S3 (no dollar figure cited for craft under 40m) interpolated per the note above.
_YACHT_HULL_VALUE_BY_TIER = {
    "S1": 300_000, "S2": 1_500_000, "S3": 5_000_000, "S4": 10_000_000,
    "S5": 25_000_000, "S6": 60_000_000, "S7": 130_000_000,
}

BASELINE_LIMIT_USD = {
    # ---- yacht (tiered off _YACHT_HULL_VALUE_BY_TIER; S1-S7) ----
    ("yacht", "hull_machinery"): {"by_tier": dict(_YACHT_HULL_VALUE_BY_TIER)},
    # cited explicit floor $5M for S1-S3, scaling to cited $25M+ ceiling by S7 — linear step.
    ("yacht", "liability_protection"): {"by_tier": {
        "S1": 5_000_000, "S2": 5_000_000, "S3": 5_000_000,
        "S4": 10_000_000, "S5": 15_000_000, "S6": 20_000_000, "S7": 25_000_000,
    }},
    # "no aggregate cap set below crew complement x per-head figure" — per-head floor of the
    # cited $1,000,000-$2,000,000 range x CREW_COMPLEMENT_BY_SIZE (both cited in this same
    # entry's own prose), midpoint $1,500,000/head.
    ("yacht", "crew_medical_mlc"): {"by_tier": {
        "S1": 3_000_000, "S2": 4_500_000, "S3": 9_000_000, "S4": 13_500_000,
        "S5": 19_500_000, "S6": 25_500_000, "S7": 36_000_000,
    }},
    # "Matched to the vessel's full Agreed Hull Value (same limit as Hull & Machinery)" — verbatim.
    ("yacht", "marine_war_risk"): {"by_tier": dict(_YACHT_HULL_VALUE_BY_TIER)},
    # "Typically 20-30% of the vessel's total agreed hull value ... for S5+ tiers" — 25%
    # midpoint x hull value, applied across all tiers for table completeness (S1-S4 below the
    # prose's explicit S5+ scope, flagged as extrapolated at the same ratio).
    ("yacht", "increased_value_excess_liabilities"): {"by_tier": {
        k: round(v * 0.25 / 1000) * 1000 for k, v in _YACHT_HULL_VALUE_BY_TIER.items()
    }},
    # cited worked example: S5-S6 vessel at $250k-$450k/week charter -> "roughly $2,000,000-
    # $5,000,000+" limit; S5/S6 set inside that cited band, S1-S4/S7 extrapolated proportionally
    # to the same vessel-size scaling the worked example itself uses.
    ("yacht", "loss_of_charter_hire"): {"by_tier": {
        "S1": 75_000, "S2": 200_000, "S3": 600_000, "S4": 1_500_000,
        "S5": 3_000_000, "S6": 5_000_000, "S7": 8_000_000,
    }},
    # "$1,000,000 minimum COFR ... $5,000,000-$10,000,000+ ... especially larger fuel-bunker
    # capacities on S5+ tier vessels" — cited floor below S5, cited upper band S5-S7.
    ("yacht", "pollution_liability"): {"by_tier": {
        "S1": 1_000_000, "S2": 1_000_000, "S3": 1_000_000, "S4": 1_000_000,
        "S5": 5_000_000, "S6": 7_500_000, "S7": 10_000_000,
    }},
    # "$5,000,000 minimum primary for any US-flagged vessel with signed-on crew" — the prose
    # ties this to crew presence, not vessel size class, so it's flat (not tiered) — cited floor.
    ("yacht", "crew_employers_liability_jones_act"): {"flat": 5_000_000},
    # "$500,000-$10,000,000+ in aggregate for S5+ tier vessels known to carry significant
    # collections" — cited band applied to S5-S7, S1-S4 extrapolated lower (smaller vessels,
    # smaller aboard collections, same informed-practitioner discipline as the hull table).
    ("yacht", "fine_art_marine_rider"): {"by_tier": {
        "S1": 100_000, "S2": 150_000, "S3": 200_000, "S4": 250_000,
        "S5": 2_000_000, "S6": 5_000_000, "S7": 8_000_000,
    }},
    # "$10,000,000-$25,000,000 minimum excess layer for S4+ tier vessels ... scaling toward
    # $50,000,000+ for S6-S7 tier vessels" — cited floor at S4, cited ceiling at S7, S5/S6
    # interpolated between; S1-S3 (below the prose's explicit S4+ scope) extrapolated lower.
    ("yacht", "excess_umbrella_liability"): {"by_tier": {
        "S1": 2_000_000, "S2": 5_000_000, "S3": 8_000_000, "S4": 10_000_000,
        "S5": 17_500_000, "S6": 35_000_000, "S7": 50_000_000,
    }},

    # ---- aviation (tiered by pricing_v2.aviation_tier(): light/mid/heavy) ----
    # "$5,000,000-$20,000,000 for a light/midsize jet and $30,000,000-$75,000,000+ for a
    # large-cabin/ultra-long-range jet" — light/mid split within the first cited band (this
    # project's own pricing tier already separates "light" from "mid"), heavy inside the second.
    ("aviation", "aviation_hull"): {"by_tier": {"light": 8_000_000, "mid": 15_000_000, "heavy": 50_000_000}},
    # "$100,000,000 CSL ... market-standard floor for a mid/large-cabin private jet, scaling to
    # $300,000,000+" — mid = cited floor, heavy = between the cited floor and ceiling, light
    # extrapolated lower (below the prose's explicit mid/large-cabin scope).
    ("aviation", "aviation_liability"): {"by_tier": {"light": 50_000_000, "mid": 100_000_000, "heavy": 200_000_000}},
    # "$1,000,000 AD&D per crew position minimum" — the cited figure specific to THIS
    # coverage_type_id (loss_of_license below carries its own separate cited figure) — flat.
    ("aviation", "crew_accident"): {"flat": 1_000_000},
    # "War Liability = matched to the aircraft's full aviation_liability limit" — verbatim.
    ("aviation", "war_risk"): {"by_tier": {"light": 50_000_000, "mid": 100_000_000, "heavy": 200_000_000}},
    # "$10,000,000-$25,000,000 combined single limit as a standalone policy" — no tier scaling
    # cited (this line exists specifically to backstop third-party/charter-operator gaps
    # regardless of the insured's own aircraft class) — cited floor, flat.
    ("aviation", "non_owned_aircraft_liability"): {"flat": 10_000_000},
    # "never less than aviation_hull's stated value ... sized to the full hull value" — verbatim
    # tie to aviation_hull's own tier table.
    ("aviation", "hangarkeepers_liability"): {"by_tier": {"light": 8_000_000, "mid": 15_000_000, "heavy": 50_000_000}},
    # "$1,000,000-$2,500,000 lump-sum ... for a captain of a large-cabin jet" — not tiered by
    # hull size in the prose (framed as one range) — cited floor, flat.
    ("aviation", "loss_of_license"): {"flat": 1_000_000},
    # "$250,000-$500,000 per seat, matched to the aircraft's certified passenger seating
    # configuration" — per-seat floor x typical seating count per tier (light~8/mid~12/heavy~16,
    # ordinary cabin-class seating convention, since seat count itself isn't in this dataset).
    ("aviation", "guest_voluntary_settlement"): {"by_tier": {"light": 2_000_000, "mid": 3_000_000, "heavy": 4_000_000}},
    # "Matches or exceeds aviation_liability's full limit (commonly $100,000,000+)" — verbatim
    # tie to aviation_liability's own tier table.
    ("aviation", "trustee_additional_insured_indemnity"): {"by_tier": {"light": 50_000_000, "mid": 100_000_000, "heavy": 200_000_000}},

    # ---- real_estate (flat — Asset rows carry size_class="N/A" for this vertical) ----
    ("real_estate", "coastal_wind_flood"): {"flat": 10_000_000},
    ("real_estate", "high_value_property"): {"flat": 5_000_000},
    ("real_estate", "premises_liability"): {"flat": 5_000_000},
    ("real_estate", "excess_umbrella_liability"): {"flat": 25_000_000},
    # "$4,750,000+ excess layer minimum (to build a $5,000,000 total flood tower)" — cited.
    ("real_estate", "excess_flood"): {"flat": 4_750_000},
    ("real_estate", "earthquake_dic"): {"flat": 5_000_000},
    # no fixed dollar minimum cited ("100% of total projected ... commonly $2,000,000-
    # $25,000,000+") — cited floor of the commonly-seen range used as the baseline.
    ("real_estate", "builders_risk_course_of_construction"): {"flat": 2_000_000},
    # "Matches the underlying high_value_property dwelling limit" — verbatim.
    ("real_estate", "vacant_unoccupied_dwelling"): {"flat": 5_000_000},
    # "$1,000,000-$3,000,000 combined ... sub-limit" — midpoint (no explicit floor emphasis
    # in the prose the way most other entries here cite one).
    ("real_estate", "equipment_breakdown_service_line"): {"flat": 2_000_000},
    # WC leg is statutory (not a clean $ figure); EPLI leg cited "$1,000,000-$3,000,000" —
    # midpoint of the EPLI figure used as the clean-number baseline.
    ("real_estate", "domestic_staff_liability"): {"flat": 2_000_000},
    ("real_estate", "environmental_pollution_liability"): {"flat": 3_000_000},

    # ---- auto (flat — Asset rows carry size_class="N/A" for this vertical) ----
    # "commonly $250,000-$20,000,000+" per-vehicle — cited per-vehicle floor.
    ("auto", "agreed_value_fleet"): {"flat": 250_000},
    ("auto", "transit"): {"flat": 5_000_000},
    ("auto", "garage_keepers"): {"flat": 5_000_000},
    # "Recommended UHNW baseline: $1,000,000 combined single limit (CSL) per vehicle" — cited verbatim.
    ("auto", "auto_liability"): {"flat": 1_000_000},
    # "Should match the underlying auto_liability limit dollar-for-dollar" — verbatim tie.
    ("auto", "uninsured_underinsured_motorist"): {"flat": 1_000_000},
    ("auto", "excess_umbrella_liability"): {"flat": 10_000_000},
    # "liability sublimit commonly $1,000,000-$5,000,000 per event" — cited floor (physical
    # damage leg reinstates the primary schedule's own agreed value, not an independent number).
    ("auto", "track_day_competition_use"): {"flat": 1_000_000},
    # "budget 10-20% of the vehicle's agreed value" — no fixed dollar anchor of its own; 15%
    # midpoint applied to THIS SAME table's agreed_value_fleet per-vehicle floor ($250,000).
    ("auto", "spare_parts_automobilia"): {"flat": 40_000},
    # no ratio or fixed figure cited at all (reporting-form, cost-to-date convention only);
    # set at 50% of agreed_value_fleet's own per-vehicle floor as a representative
    # "mid-project" cost-to-date figure, grounded in this same table's own cited number.
    ("auto", "restoration_work_in_progress"): {"flat": 125_000},

    # ---- personal (flat — Asset rows carry size_class="N/A" for this vertical) ----
    ("personal", "kr"): {"flat": 5_000_000},
    ("personal", "exec_do"): {"flat": 5_000_000},
    ("personal", "cyber_crime"): {"flat": 3_000_000},
    ("personal", "blanket_personal_articles"): {"flat": 250_000},
    ("personal", "personal_excess_liability"): {"flat": 25_000_000},
    ("personal", "domestic_staff_epli"): {"flat": 1_000_000},
    ("personal", "household_workers_comp"): {"flat": 1_000_000},
    ("personal", "family_office_fiduciary_liability"): {"flat": 5_000_000},
    ("personal", "travel_medical_evacuation"): {"flat": 1_000_000},
    ("personal", "personal_cyber_liability"): {"flat": 1_000_000},

    # ---- fine_art (flat, hand-authored entry below — Asset rows carry size_class="N/A") ----
    ("fine_art", "fine_art_scheduled"): {"flat": 500_000},
}


def _baseline_fields_for(vertical, coverage_type_id):
    """Returns (baseline_limit_usd, baseline_limit_by_tier) for a COVERAGE_CATALOG entry from
    the BASELINE_LIMIT_USD table above. flat -> (number, None); by_tier -> (None, dict)."""
    spec = BASELINE_LIMIT_USD.get((vertical, coverage_type_id))
    if spec is None:
        return None, None
    if "flat" in spec:
        return spec["flat"], None
    return None, dict(spec["by_tier"])


def _merge_coverage_entry(vertical, e):
    baseline_flat, baseline_by_tier = _baseline_fields_for(vertical, e["coverage_type_id"])
    return {
        "coverage_type_id": e["coverage_type_id"],
        "label": e["label"],
        "trigger_type": e["trigger_type"],
        "line_of_business": e["line_of_business"],
        "is_new": e.get("is_new", False),
        "required_baseline_limit": e.get("required_baseline_limit", ""),
        "baseline_limit_usd": baseline_flat,
        "baseline_limit_by_tier": baseline_by_tier,
        "statutory_triggers": json.loads(e["statutory_triggers"]) if e.get("statutory_triggers") else [],
        "sub_limit_exclusions": json.loads(e["sub_limit_exclusions"]) if e.get("sub_limit_exclusions") else [],
        "cascade_rules": json.loads(e["cascade_rules"]) if e.get("cascade_rules") else [],
        "note": _COVERAGE_CATALOG_NOTES.get((vertical, e["coverage_type_id"]), ""),
    }


COVERAGE_CATALOG = {
    block["vertical"]: [_merge_coverage_entry(block["vertical"], e) for e in block["coverage_entries"]]
    for block in _COVERAGE_RESEARCH
}

# fine_art vertical was out of scope for the 5-vertical research fan-out (it's its own
# single-domain scheduled-property program, not a lifecycle asset — see DOMAINS_BY_VERTICAL
# above) — carries the same 4 new fields, authored directly, consistent with the existing
# RATE_TREND_BY_COVERAGE_TYPE note that no fine-art-specific index was ever found either.
COVERAGE_CATALOG["fine_art"] = [
    {
        "coverage_type_id": "fine_art_scheduled", "label": "Fine Art (Scheduled)", "trigger_type": "asset",
        "line_of_business": "Personal Lines", "is_new": False,
        "required_baseline_limit": (
            "Scheduled item-by-item at current appraised/replacement value, typically $500,000-$25,000,000+ "
            "in aggregate for a genuine UHNW collection — no blanket cap, since the schedule itself IS the "
            "limit (brief §6 item 6: fine art is its own asset class with a situs, not nested under Yacht). "
            "Reassessed at each renewal on a 3-5 year appraisal cadence, matching blanket_personal_articles' "
            "own re-appraisal convention for high-value scheduled items."
        ),
        # cited floor of the "$500,000-$25,000,000+" aggregate range — flat (fine_art Assets
        # carry size_class="N/A", same convention as BASELINE_LIMIT_USD above).
        "baseline_limit_usd": BASELINE_LIMIT_USD[("fine_art", "fine_art_scheduled")]["flat"],
        "baseline_limit_by_tier": None,
        "statutory_triggers": [],
        "sub_limit_exclusions": [
            {"type": "exclusion", "detail": "Wear and tear, gradual deterioration, inherent vice, and restoration/repair damage excluded — this is a physical-loss policy, not a conservation warranty."},
            {"type": "exclusion", "detail": "War and nuclear exclusion, standard market-wide."},
            {"type": "condition", "detail": "Coverage is situs-specific to the scheduled location(s); an item moved to an unscheduled location (including aboard a yacht) without notice can fall outside cover — see fine_art_marine_rider for the yacht-specific gap this creates."},
            {"type": "sub_limit", "detail": "Pairs-and-sets clause limits recovery to the proportional value of a lost item from a matched set rather than the full set's value."},
        ],
        "cascade_rules": [
            {"condition": "scheduled items are ever transported aboard the account's yacht", "implies": "fine_art_marine_rider (yacht vertical) is likely needed — this policy's situs-specific exclusion does not follow the collection to sea."},
            {"condition": "account also carries blanket_personal_articles (personal vertical)", "implies": "confirm no double-scheduling of the same item across both policies — fine art and jewelry/watches/furs are typically kept on separate schedules with separate appraisal cadences."},
        ],
        "note": "",
    },
]

# ============================================================================
# §7 — GWP pricing engine, corrected. Rate trends are REAL cited figures (Marsh GIMI Q2 2026,
# IUMI Stats Report 2025) where found; everything else is an explicitly labeled estimate.
# as-of date + source stamped on every trend for auditability (brief §7.3).
# ============================================================================
RATE_TABLE_AS_OF = "2026-Q2 (Marsh Global Insurance Market Index) / 2025 (IUMI Stats Report)"

RATE_TREND_BY_COVERAGE_TYPE = {
    # coverage_type_id: (pct, source_label)
    "hull_machinery": (0.035, "IUMI Stats Report 2025 — Ocean Hull premium +3.5%"),
    "liability_protection": (0.015, "IUMI Stats Report 2025 — Marine global premium +1.5%"),
    "crew_medical_mlc": (0.0, "[NO SOURCE FOUND — ESTIMATE] MLC-driven, not market-rate-driven; held flat, priced via Parameter Multiplier instead"),
    "aviation_hull": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-hull-specific index cited in brief §7"),
    "aviation_liability": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-liability-specific index cited in brief §7"),
    "crew_accident": (0.02, "[NO SOURCE FOUND — ESTIMATE]"),
    "war_risk": (0.02, "[NO SOURCE FOUND — ESTIMATE]"),
    "coastal_wind_flood": (-0.12, "Marsh GIMI Q2 2026 — global Property composite -12%"),
    "high_value_property": (-0.12, "Marsh GIMI Q2 2026 — global Property composite -12%"),
    "premises_liability": (0.07, "Marsh GIMI Q2 2026 — US Casualty +7% (the one in-range figure, one line/region)"),
    "agreed_value_fleet": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "transit": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "garage_keepers": (0.07, "Marsh GIMI Q2 2026 — US Casualty +7% (garage keepers modeled as casualty-adjacent)"),
    "kr": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "exec_do": (0.02, "Marsh GIMI Q2 2026 — global Casualty +2% (D&O modeled as casualty-adjacent, entity-triggered)"),
    "cyber_crime": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "blanket_personal_articles": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "fine_art_scheduled": (0.02, "[NO SOURCE FOUND — ESTIMATE] no fine-art-specific index found; conservative placeholder"),

    # ---- 2026-08-16 catalog extension (coverage_research_v2.json) — 30 new coverage_type_ids.
    # Real citations reused ONLY where an analogous line in this same table already cites one
    # (e.g. exec_do/garage_keepers modeled as casualty-adjacent off Marsh GIMI US Casualty +7%
    # or global Casualty +2%) — never a fabricated new external source. Everything else flagged
    # [NO SOURCE FOUND — ESTIMATE], same discipline as the original 18-entry table above.
    # yacht (7 new)
    "marine_war_risk": (0.02, "[NO SOURCE FOUND — ESTIMATE] no marine-war-risk-specific index cited; held near aviation war_risk's own estimate"),
    "increased_value_excess_liabilities": (0.035, "[NO SOURCE FOUND — ESTIMATE] follows hull_machinery's IUMI Stats Report 2025 Ocean Hull +3.5% trend — IV is a follow-form layer atop hull, not an independently rated line"),
    "loss_of_charter_hire": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "pollution_liability": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "crew_employers_liability_jones_act": (0.07, "Marsh GIMI Q2 2026 — US Casualty +7% (Jones Act crew liability modeled as casualty-adjacent, same convention as garage_keepers)"),
    "fine_art_marine_rider": (0.02, "[NO SOURCE FOUND — ESTIMATE] no fine-art-specific index found; conservative placeholder, consistent with fine_art_scheduled"),
    "excess_umbrella_liability": (0.02, "Marsh GIMI Q2 2026 — global Casualty +2% (excess/umbrella modeled as casualty-adjacent, same convention as exec_do; shared coverage_type_id across yacht/real_estate/auto verticals)"),
    # aviation (5 new) — no aviation-specific index exists anywhere in this table (brief §7); held at the same flat estimate as aviation_hull/aviation_liability/crew_accident/war_risk
    "non_owned_aircraft_liability": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-specific index cited in brief §7"),
    "hangarkeepers_liability": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-specific index cited in brief §7"),
    "loss_of_license": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-specific index cited in brief §7"),
    "guest_voluntary_settlement": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-specific index cited in brief §7"),
    "trustee_additional_insured_indemnity": (0.02, "[NO SOURCE FOUND — ESTIMATE] no aviation-specific index cited in brief §7"),
    # real_estate (8 new; excess_umbrella_liability already defined above, shared across verticals)
    "excess_flood": (-0.12, "Marsh GIMI Q2 2026 — global Property composite -12% (private excess flood follows the same primary property market conditions as coastal_wind_flood)"),
    "earthquake_dic": (0.0, "[NO SOURCE FOUND — ESTIMATE] catastrophe-exposed segment often diverges from the broader property composite; held flat pending a seismic-specific index"),
    "builders_risk_course_of_construction": (0.0, "[NO SOURCE FOUND — ESTIMATE] project-based one-off placement, not a renewal-rated line"),
    "vacant_unoccupied_dwelling": (0.0, "[NO SOURCE FOUND — ESTIMATE] endorsement premium is typically a nominal add-on, not independently trended"),
    "equipment_breakdown_service_line": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "domestic_staff_liability": (0.07, "Marsh GIMI Q2 2026 — US Casualty +7% (household employer WC+EPLI bundle modeled as casualty-adjacent, same convention as garage_keepers)"),
    "environmental_pollution_liability": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    # auto (6 new; excess_umbrella_liability already defined above, shared across verticals)
    "auto_liability": (0.07, "Marsh GIMI Q2 2026 — US Casualty +7% (personal auto liability modeled as casualty-adjacent, same convention as garage_keepers)"),
    "uninsured_underinsured_motorist": (0.07, "[NO SOURCE FOUND — ESTIMATE] follows auto_liability's Marsh GIMI Q2 2026 US Casualty +7% — UM/UIM is typically written matched to the BI limit it rides alongside"),
    "track_day_competition_use": (0.03, "[NO SOURCE FOUND — ESTIMATE] explicit gap — the coverage type most directly implicated by the auto vertical's own track/competition scope, per research"),
    "spare_parts_automobilia": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "restoration_work_in_progress": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    # personal (6 new)
    "personal_excess_liability": (0.02, "Marsh GIMI Q2 2026 — global Casualty +2% (personal umbrella modeled as casualty-adjacent, same convention as exec_do)"),
    "domestic_staff_epli": (0.07, "Marsh GIMI Q2 2026 — US Casualty +7% (household employment-practices liability modeled as casualty-adjacent, same convention as garage_keepers/domestic_staff_liability)"),
    "household_workers_comp": (0.0, "[NO SOURCE FOUND — ESTIMATE] statutory-benefit-driven, not market-rate-driven; held flat, same convention as crew_medical_mlc"),
    "family_office_fiduciary_liability": (0.02, "Marsh GIMI Q2 2026 — global Casualty +2% (RIA/fiduciary E&O modeled as casualty-adjacent, same convention as exec_do)"),
    "travel_medical_evacuation": (0.03, "[NO SOURCE FOUND — ESTIMATE]"),
    "personal_cyber_liability": (0.03, "[NO SOURCE FOUND — ESTIMATE] held at cyber_crime's own estimate — no personal-cyber-specific index found either"),
}

# Parameter Multiplier per-head rate for Crew Medical (MLC) — brief §7.5: pattern is sound
# (NCCI exposure-base x classification-rate shape) but no specific per-head $ was cited.
# $2,300/head is reverse-derived from this project's own existing bound data
# (COV.WHISPER.CREWMED = $41,800 bound for an implied ~18-crew S6 vessel) and held as the
# labeled estimate, version-stamped per brief §7.5's "version/date-stamp the rate table" fix.
CREW_MEDICAL_PER_HEAD_RATE = 2300
CREW_MEDICAL_RATE_VERSION = "v2026.1 — reverse-derived from existing bound COV.WHISPER.CREWMED, not independently sourced"
# Crew complement estimate by size class (STCW/MLC-consistent order of magnitude, not a cited table)
CREW_COMPLEMENT_BY_SIZE = {"S1": 2, "S2": 3, "S3": 6, "S4": 9, "S5": 13, "S6": 17, "S7": 24}

# MLC 2006 Reg 4.2 / Std A4.2.1 16-week minimum wage-continuation floor — brief §7.5 sanity check,
# NOT a rate: flag if a Crew Medical policy's stated limit implies less than ~16 weeks of coverage
# continuation. Recorded here as a fixed reference constant for the sanity-check function.
MLC_WAGE_CONTINUATION_FLOOR_WEEKS = 16

COV_TYPE_SHORT_CODE = {
    "hull_machinery": "HULL", "liability_protection": "LIAB", "crew_medical_mlc": "CREWMED",
    "aviation_hull": "AVHULL", "aviation_liability": "AVLIAB", "crew_accident": "CREWACC", "war_risk": "WAR",
    "coastal_wind_flood": "WINDFLD", "high_value_property": "PROP", "premises_liability": "PREMLIAB",
    "agreed_value_fleet": "FLEET", "transit": "TRANSIT", "garage_keepers": "GARAGE",
    "kr": "KR", "exec_do": "EXECDO", "cyber_crime": "CYBER", "blanket_personal_articles": "BLANKET",
    "fine_art_scheduled": "FINEART",

    # 2026-08-16 catalog extension — 30 new coverage_type_ids. Short codes need only be unique
    # WITHIN a vertical's own coverage id string (COV.<surname>.<vertical-abbr>.<shortcode>), so
    # excess_umbrella_liability sharing one code across yacht/real_estate/auto is fine — the
    # vertical-abbr segment already disambiguates COV.X.YACHT.EXCUMB from COV.X.AUTO.EXCUMB.
    "marine_war_risk": "WARPIR", "increased_value_excess_liabilities": "IVEXCESS",
    "loss_of_charter_hire": "CHARHIRE", "pollution_liability": "POLLUTE",
    "crew_employers_liability_jones_act": "JONESACT", "fine_art_marine_rider": "ARTMARINE",
    "excess_umbrella_liability": "EXCUMB",
    "non_owned_aircraft_liability": "NONOWNAC", "hangarkeepers_liability": "HANGARKPR",
    "loss_of_license": "LOL", "guest_voluntary_settlement": "GUESTVOL",
    "trustee_additional_insured_indemnity": "TRUSTEEAI",
    "excess_flood": "EXFLOOD", "earthquake_dic": "QUAKE",
    "builders_risk_course_of_construction": "BUILDRISK", "vacant_unoccupied_dwelling": "VACANT",
    "equipment_breakdown_service_line": "EQBRKDN", "domestic_staff_liability": "DOMSTAFF",
    "environmental_pollution_liability": "ENVPOLL",
    "auto_liability": "AUTOLIAB", "uninsured_underinsured_motorist": "UMUIM",
    "track_day_competition_use": "TRACKDAY", "spare_parts_automobilia": "SPAREPRT",
    "restoration_work_in_progress": "RESTOWIP",
    "personal_excess_liability": "PEREXCESS", "domestic_staff_epli": "EPLI",
    "household_workers_comp": "HHWORKCMP", "family_office_fiduciary_liability": "FOFIDUC",
    "travel_medical_evacuation": "MEDEVAC", "personal_cyber_liability": "PERCYBER",
}

PEER_COMP_CONFIDENCE_BANDS = [(15, "high"), (5, "medium"), (0, "low")]  # (min_n, tier), checked descending


def peer_comp_confidence(n):
    for min_n, tier in PEER_COMP_CONFIDENCE_BANDS:
        if n >= min_n:
            return tier
    return "low"


# relationship_weight ring-gated formula — brief §6 item 9. Multipliers are an EXPLICIT
# ESTIMATE ("no source validates these exact five numbers") pending real usage data.
RING_AUTHORITY_MULTIPLIER = {0: 1.0, 1: 0.85, 2: 0.55, 3: 0.25, 4: 0.12}
RELATIONSHIP_WEIGHT_W_ACTIVITY = 0.6
RELATIONSHIP_WEIGHT_W_RECENCY = 0.4

# ============================================================================
# Producers (5 — adds "Naomi," the 5th archetype from 01-plan/influence720-dashboard-plan.md's
# "The Rookie" that the prior build never implemented) + Leadership (unchanged).
# ============================================================================
PRODUCERS = [
    {"producer_id": "REP.ALEX", "name": "Alex", "archetype": "High-Yield, Low-Touch", "region": "South Florida",
     "narrative": "80% Ring 1/2 signatories, massive GWP. The ideal state — talks to fewer people, exclusively economic buyers.",
     "touchpoints_90d": 22, "gwp_captured_90d": 1850000, "pct_touches_ring1_2": 0.80,
     "touchpoints_90d_prior": 26, "gwp_captured_90d_prior": 1510000, "churn_risk_score": 1.2},
    {"producer_id": "REP.RAHUL", "name": "Rahul", "archetype": "High-Touch, Low-Yield", "region": "South Florida",
     "narrative": "90% Ring 3/4 operational/crew, low GWP. Massive activity, almost none of it lands on a signatory.",
     "touchpoints_90d": 210, "gwp_captured_90d": 240000, "pct_touches_ring1_2": 0.10,
     "touchpoints_90d_prior": 188, "gwp_captured_90d_prior": 255000, "churn_risk_score": 2.0},
    {"producer_id": "REP.JACOB", "name": "Jacob", "archetype": "Legacy Book, Decaying Contact", "region": "South Florida",
     "narrative": "Massive GWP, but comm-frequency is decaying. Bound large accounts years ago, hasn't spoken to the Ring 1 signatory in 8 months.",
     "touchpoints_90d": 9, "gwp_captured_90d": 2100000, "pct_touches_ring1_2": 0.35,
     "touchpoints_90d_prior": 21, "gwp_captured_90d_prior": 2140000, "churn_risk_score": 8.6},
    {"producer_id": "REP.CRISTIAN", "name": "Cristian", "archetype": "Single-Vertical Concentration", "region": "South Florida",
     "narrative": "100% single-vertical GWP, zero adjacent policies. Has the Ring 1 ear of the UBO, leaves the cross-pollination money on the table.",
     "touchpoints_90d": 60, "gwp_captured_90d": 680000, "pct_touches_ring1_2": 0.75,
     "touchpoints_90d_prior": 58, "gwp_captured_90d_prior": 665000, "churn_risk_score": 1.8},
    {"producer_id": "REP.NAOMI", "name": "Naomi", "archetype": "High Activity, Unmapped Network", "region": "South Florida",
     "narrative": "High activity, calling largely unmapped Ring 3/4 contacts on cold accounts. Needs the Tier 1 referral web to find the warm path to the actual decision-makers.",
     "touchpoints_90d": 145, "gwp_captured_90d": 310000, "pct_touches_ring1_2": 0.18,
     "touchpoints_90d_prior": 98, "gwp_captured_90d_prior": 190000, "churn_risk_score": 3.4},
]

LEADERSHIP = [
    {"leader_id": "LEAD.JONATHAN", "name": "Jonathan", "title": "Regional Director", "scope": "South Florida region — team lead tier, sees all 5 producers"},
    {"leader_id": "LEAD.TRISH", "name": "Trish", "title": "SVP", "scope": "Executive — sees the full regional roll-up"},
]

# ============================================================================
# Name pools for the 143 new accounts + their role-instances — staged/fake, consistent with
# every existing name in this project (all data in this repo is explicitly mock/illustrative).
# ============================================================================
FAMILY_SURNAMES = [
    "Ashworth", "Beaumont", "Carrington", "Delacroix", "Ellsworth", "Fairweather", "Grosvenor", "Hartley",
    "Ivanovic", "Jarnac", "Kensington", "Lindqvist", "Northcote", "Ogilvie", "Pemberton", "Quintrell",
    "Ravensworth", "Sinclair", "Thornbury", "Underhill", "Vandermeer", "Whitmore", "Yardley", "Zamora",
    "Ashcombe", "Blackwood", "Chastain", "Devereux", "Everleigh", "Fenwick", "Grantham", "Halloway",
    "Isherwood", "Kilbride", "Lachance", "Moreau", "Nightingale", "Osgood", "Prentiss", "Radcliffe",
    "Stavros", "Trevelyan", "Ballantine", "Cavanaugh", "Drummond", "Esterhazy", "Fitzwilliam", "Greville",
    "Harcourt", "Inglewood", "Kirkbride", "Loxley", "Montfort", "Norwood", "Pelham", "Rothbury",
    "Standish", "Talbot", "Uxbridge", "Verlaine", "Wentworth", "Alderton", "Bramwell", "Castellan",
    "Dunmore", "Elphinstone", "Foxleigh", "Gainsborough", "Hollowell", "Iverson", "Jessop", "Killigrew",
    "Lansdowne", "Merrivale", "Overbury", "Penhallow", "Rutherglen", "Sedgemoor", "Thistlewood", "Ancaster",
    "Brackenridge", "Comberford", "Devenport", "Eastcott", "Farleigh", "Gattenby", "Hexham", "Ingleby",
]

FIRST_NAMES = [
    "James", "Olivia", "William", "Sophia", "Henry", "Amelia", "Charles", "Isla", "Edward", "Grace",
    "Theodore", "Charlotte", "Arthur", "Eleanor", "Frederick", "Beatrice", "Julian", "Margot", "Sebastian", "Clara",
    "Nathaniel", "Rosalind", "Alexander", "Vivienne", "Benjamin", "Cecilia", "Christopher", "Adelaide", "Dominic", "Josephine",
    "Gabriel", "Marguerite", "Lucas", "Genevieve", "Maximilian", "Isabelle", "Anthony", "Camille", "Rupert", "Odette",
    "Desmond", "Wilhelmina", "Percival", "Constance", "Reginald", "Theodora", "Bartholomew", "Anastasia", "Cornelius", "Seraphina",
    "Marcus", "Ines", "Julian", "Priyanka", "Diego", "Naledi", "Ravi", "Fatima", "Kenji", "Amara",
]

YACHT_NAMES = [
    "Meridian", "Solace", "Wanderlust", "Serein", "Nautilus", "Cascade", "Elysian", "Zenith",
    "Tranquil", "Odyssey", "Aria", "Borealis", "Cielo", "Drift", "Ember", "Fathom", "Gale",
    "Horizon", "Isolde", "Juno", "Kestrel", "Lumina", "Mirage", "Nomad", "Orion", "Pinnacle",
    "Quill", "Ravel", "Sirocco", "Talisman", "Umbra", "Vesper", "Wraith", "Amara", "Bellwether",
    "Crescendo", "Denali", "Ethereal", "Flourish", "Genesis", "Halcyon II", "Infinite", "Jubilee",
    "Kinship", "Meridian Voyager", "Mistral", "Nirvana", "Opaline", "Peregrine", "Quintessa", "Radiance",
]

STAFF_SURNAMES = [
    "Doyle", "Rees", "Deshmukh", "Brandt", "Whitfield", "Marsh", "Kellerman", "Foster", "Solis", "Ngata",
    "Okafor", "Aldridge", "Pratt", "Vance", "Doherty", "Marchbanks", "Okonjo", "Feathering", "Larkspur", "Yeun",
    "Abernathy", "Bellweather", "Castellane", "Dunleavy", "Ekwueme", "Farrow", "Giannopoulos", "Holloway", "Iyer", "Jarrett",
    "Kowalczyk", "Lindgren", "Mercado", "Nakamura", "O'Farrell", "Petrosyan", "Quimby", "Renner", "Salazar", "Tremblay",
]

random.seed(720720)


def unique_surname_pool(n):
    """Generate n unique account surnames, single names first, then compound for overflow."""
    pool = list(FAMILY_SURNAMES)
    random.shuffle(pool)
    names = list(pool[:n])
    if len(names) < n:
        remaining = n - len(names)
        combos = []
        shuffled2 = list(FAMILY_SURNAMES)
        random.shuffle(shuffled2)
        for i in range(len(pool)):
            for j in range(len(shuffled2)):
                if pool[i] != shuffled2[j]:
                    combos.append(f"{pool[i]}-{shuffled2[j]}")
        random.shuffle(combos)
        seen = set(names)
        for c in combos:
            if c not in seen:
                names.append(c)
                seen.add(c)
            if len(names) >= n:
                break
    return names[:n]


if __name__ == "__main__":
    import os
    os.makedirs(BUILD_DIR, exist_ok=True)
    with open(f"{BUILD_DIR}/_smoke_test.json", "w") as f:
        json.dump({
            "domains_by_vertical_keys": list(DOMAINS_BY_VERTICAL.keys()),
            "role_taxonomy_counts": {v: len(r) for v, r in ROLE_TAXONOMY.items()},
            "coverage_catalog_counts": {v: len(c) for v, c in COVERAGE_CATALOG.items()},
            "producer_count": len(PRODUCERS),
            "sample_surnames": unique_surname_pool(10),
        }, f, indent=2)
    print("foundation_v2 smoke test OK")
