"""
Merges the vertical-ontology-expansion Workflow's output (real 26-34-role taxonomies spanning
all 9 canonical lifecycle segments for aviation/real_estate/auto/personal, plus a hand-remapped
yacht taxonomy reusing 360's own 32 roles) into foundation_v2.py's ROLE_TAXONOMY, and writes the
standalone TEMPLATE ontology (role + structural-edge data, NOT tied to any of the 150 accounts —
this is the "first iteration before D1" structural backbone, one per vertical, analogous to 360
itself) to a new JSON the Excel/JS emitters read from.

Previously: 8 categories, flattened (aviation/auto/personal/real_estate each had exactly ONE
category regardless of role), reused nowhere consistently with 360's own 9-domain scheme. Now:
9 canonical segments (a direct generalization of 360's own 9 domain names/ids/colors), populated
for every vertical including yacht itself (which previously only used 7 of its own 9 domains —
Acquisition & Disposal and Build/Fit-Out & Refit had ZERO roles in the prior taxonomy).
"""
import json

RESULT_PATH = "/private/tmp/claude-501/-Users-celeste7/a4eedd11-2615-4b11-a3c1-eaa58ca40bfe/scratchpad/vertical_ontology_result.json"
OUT_TEMPLATE_ONTOLOGY = "template_ontology.json"
OUT_ROLE_TAXONOMY_PY = "role_taxonomy_generated.py"

VERTICALS_ORDER = ["aviation", "real_estate", "auto", "personal"]

RING_TO_COI_TYPE = {0: "signatory", 1: "signatory", 2: "conditional", 3: "transaction", 4: "operational"}
# Compliance/certification and insurance-market-adjacent roles read as regulatory/adjacent in the
# original taxonomy's own vocabulary, regardless of ring — preserves that distinction.
SEGMENT_COI_OVERRIDE = {
    "Compliance & Certification": "regulatory",
    "Insurance & Risk Market": "adjacent",
    "Acquisition & Disposal": "adjacent",
}


def coi_type_for(ring, segment):
    if segment in SEGMENT_COI_OVERRIDE and ring >= 2:
        return SEGMENT_COI_OVERRIDE[segment]
    return RING_TO_COI_TYPE.get(ring, "conditional")


def main():
    with open(RESULT_PATH) as f:
        result = json.load(f)

    segments = result["segments"]
    seg_name_to_id = {s["name"]: s["id"] for s in segments}

    # ---- Yacht: hand-remapped 32-role list (from the workflow's own worked example, which is
    # 360's real roles re-segmented onto the 9 canonical names — no new content, pure relabel) ----
    yacht_roles = result["yacht"]["roles"]

    # ---- The 4 researched verticals ----
    role_taxonomy_new = {}
    template_ontology = {"segments": segments, "verticals": {}}

    def build_vertical(vertical, roles, edges):
        tuples = []
        for r in roles:
            seg_id = seg_name_to_id[r["segment"]]
            coi_type = coi_type_for(r["ring"], r["segment"])
            tuples.append((r["title"], r["ring"], coi_type, seg_id, r["segment"]))
        role_taxonomy_new[vertical] = tuples
        template_ontology["verticals"][vertical] = {
            "roles": [{"title": r["title"], "segment": r["segment"], "ring": r["ring"],
                       "rationale": r.get("rationale", "")} for r in roles],
            "edges": [{"from_title": e["from_title"], "to_title": e["to_title"],
                       "why": e["why"], "freq": e["freq"]} for e in edges],
        }

    # Yacht uses its own worked-example list directly (no separate edges researched for yacht —
    # 360's OWN real knows_edges already exist and are reused as-is downstream, not regenerated).
    build_vertical("yacht", yacht_roles, [])

    for i, v in enumerate(VERTICALS_ORDER):
        roleset = result["roles"][i]
        edgeset = result["edges"][i]
        build_vertical(v, roleset["roles"], edgeset["edges"])

    with open(OUT_TEMPLATE_ONTOLOGY, "w") as f:
        json.dump(template_ontology, f, indent=2)

    # ---- Emit a Python module foundation_v2.py can import and use to REPLACE ROLE_TAXONOMY ----
    with open(OUT_ROLE_TAXONOMY_PY, "w") as f:
        f.write('"""GENERATED by integrate_vertical_ontology.py — do not hand-edit. Re-run the '
                'vertical-ontology-expansion Workflow + this script to regenerate."""\n\n')
        f.write("ROLE_TAXONOMY = {\n")
        for v, tuples in role_taxonomy_new.items():
            f.write(f"    {v!r}: [\n")
            for t in tuples:
                f.write(f"        {t!r},\n")
            f.write("    ],\n")
        f.write("}\n\n")
        f.write("SEGMENTS = " + json.dumps(segments, indent=4) + "\n")

    counts = {v: len(t) for v, t in role_taxonomy_new.items()}
    print(f"Wrote {OUT_TEMPLATE_ONTOLOGY} and {OUT_ROLE_TAXONOMY_PY}")
    print(f"Role counts: {counts}, total={sum(counts.values())}")


if __name__ == "__main__":
    main()
